### PR TITLE
Add new prop-types dependency and update Draggable.jsx to use it

### PR DESCRIPTION
**Pull request by ryanhefner**
* Add `prop-types` dependency
* Update `Draggable.jsx` to use it
* Upgrade this so it’s supported by `react@16.*`!

### CODE REVIEW

**Comment by ryanhefner** [comment]
@mikefey ::bump:: 👋 Hope things are good!

**Comment by mikefey** [comment]
@ryanhefner Thanks, hope you're good too!

**Comment by ryanhefner** [comment]
@mikefey Yeah man, all good! Also, could you publish that update to NPM? Thanks🤘

**Comment by mikefey** [comment]
@ryanhefner good to hear! I am having troubles with NPM 2FA - I lost my keys 😬 . Trying to get it resolved but not sure when that will happen so might want to just include from Git if possible for now

**Comment by mikefey** [comment]
@ryanhefner updated!

**Pull request merged**
